jQuery(document).ready(function(){"use strict";$(window).scrollTop(4);setTimeout(function(){$('.anim-start').each(function(){$(this).removeClass('anim-start').addClass('animated');});},200);if($('.foot-anim')[0]){$('.foot-anim').footerReveal({shadow:false});if($.fn.footerReveal){$('.foot-anim').footerReveal({shadow:false});}}
$('.img-wrap').each(function(){$(this).addClass('no-loaded');$(this).find('img').one("load",function(){$(this).closest('.no-loaded').addClass('img-loaded').removeClass('no-loaded');if($('.head-anim-load .no-loaded').length==0){$('.head-anim').delay(100).addClass('animated');}}).each(function(){if(this.complete)$(this).load();});});$(window).scroll(function(){$('.anim-section').each(function(){var $window=$(window),$this=$(this),animHeight=$(this).offset().top+ $this.find('.anim-box').height()/3*2,
absHeight=($window.scrollTop()+ $window.height());if(absHeight>animHeight&&!$this.hasClass('animated')){$this.addClass('animated');}});});});if(typeof jQuery!="undefined"){$(function(){if($.isFunction($.blockUI)){$.blockUI.defaults.css.cursor="default";$.blockUI.defaults.applyPlatformOpacityRules=false;}});}
function redirect(url){window.location.href=url;}
function goToAnchor(name){var url=window.location.href;var parts=url.split("#");window.location.href=parts[0]+"#"+ name;}
function scrollToTop(){$("html, body").animate({scrollTop:0},'fast');}
function nl2br(value){return value.replace(/\r\n/g,"<br />").replace(/\n/g,"<br />").replace(/\r/g,"<br />");}
function stripTags(value){return value.replace(/<\/?[^>]+>/gi,'');}
function getAliasString(input){return input.toLowerCase().replace(/[^\w\d]+/g,'-').replace(/-{2,}/g,'-').replace(/^-/,'').replace(/-$/,'');}
function aliasCreator(fromElSelector,toElSelector){var changeAlias=function(){var alias=$(fromElSelector).val();$(toElSelector).val(getAliasString(alias));};$(fromElSelector).keyup(changeAlias);$(fromElSelector).blur(changeAlias);}
function extendClass(child,parent){var F=function(){};F.prototype=parent.prototype;child.prototype=new F();child.prototype.constructor=child;child.superclass=parent.prototype;}
var Validator={isEmpty:function(value){return value==""||value==null;},isEmail:function(value){return/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/.test(value);}};var tooltipTimeout=null;function showTooltipMessage(message,url){if(typeof jQuery!="undefined"&&$.isFunction($("body").dialog)){if($("#message-dlg").length==0){$(document.body).append("<div id=\"message-dlg\" style=\"display: none;\"></div>")}
$("#message-dlg").html(message);$("#message-dlg").dialog({title:"Message",minHeight:0,modal:true,resizable:false,buttons:{"Ok":function(){$(this).dialog("close");if(url){redirect(url);}}},close:function(event,ui){clearTimeout(tooltipTimeout);if(url){redirect(url);}}});tooltipTimeout=setTimeout(function(){$("#message-dlg").dialog("close");if(url){redirect(url);}},3000);}else{alert(message);}}
function showConfirmDlg(message,okCallback,cancelCallback){if(typeof jQuery!="undefined"&&$.isFunction($("body").dialog)){if($("#confirm-dlg").length==0){$(document.body).append("<div id=\"confirm-dlg\" style=\"display: none;\"></div>")}
$("#confirm-dlg").html(message);$("#confirm-dlg").dialog({title:"Confirm",minHeight:0,modal:true,resizable:false,buttons:{"Ok":function(){$(this).dialog("close");if($.isFunction(okCallback)){okCallback.call(this);}},"Cancel":function(){$(this).dialog("close");if($.isFunction(cancelCallback)){cancelCallback.call(this);}}}});}else{if(confirm(message)){okCallback.call(this);}else{cancelCallback.call(this);}}}
var _raqPopupCache;var _raqPopupGlobalEventsInitialized=false;function preloadRaqPopup(){if(_raqPopupCache){return;}
$.ajax({url:'/ajax/raq-popup',data:{format:"html"},async:false,success:function(data){_raqPopupCache=data;}});}
function showRaqPopup(){if(_raqPopupCache){_showRaqPopup(_raqPopupCache);_initRaqPopup();return;}
$.ajax({url:'/ajax/raq-popup',data:{format:"html"},async:false,success:function(data){_raqPopupCache=data;_showRaqPopup(data);_initRaqPopup();},error:function(){showTooltipMessage(Config.generalErrorMessage);}});}
function _initRaqPopup(){if(!_raqPopupGlobalEventsInitialized){var escapeBtnHandler=function(e){var code=e.keyCode?e.keyCode:e.which;if(code==27){$.unblockUI();}};$(document).unbind('keyup',escapeBtnHandler);$(document).keyup(escapeBtnHandler);}
_raqPopupGlobalEventsInitialized=true;$(".jq-raq-form").submit(function(){var dispatcher=new AjaxFormDispatcherJson('/ajax/submit-raq',{containerEl:".jq-raq-form-container",formEl:".jq-raq-form",successCallback:function(data){redirect('/thankyou/');},fieldsErrorsCallback:function(errors){for(var i in errors){var error=errors[i];var $element=$(".jq-raq-form [name="+ error.name+"]");$element.closest(".jq-form-row").addClass("error");var separator=", ";var msg="";if($.isArray(error.messages)){msg+=error.messages.join(separator);}else{msg+=error.messages;}
$element.closest(".jq-form-row").find("label").append(" <span>"+ msg+"</span>");}}});$(".jq-raq-form .jq-form-row").removeClass("error");$(".jq-raq-form .jq-form-row label span").remove();dispatcher.dispatch();});$(".jq-raq-form input[type=text], .jq-raq-form input[type=email], .jq-raq-form input[type=tel], .jq-raq-form textarea").focus(function(){$(this).closest(".jq-form-row").addClass("focus");}).blur(function(){$(this).closest(".jq-form-row").removeClass("focus");});}
function _showRaqPopup(html){var id="raq-popup";var selector="#"+ id;var $raq=$(selector);if($raq.length==0){$(document.body).append("<div id=\""+ id+"\" style=\"display: none;\"></div>");$raq=$(selector);}else{$raq.empty();}
$raq.html(html);$raq.find(".jq-raq-popup-verisign-container").html($(".jq-verisign-container").html());$.blockUI({message:$raq,css:{top:'50%',left:'50%',width:'632px',height:'549px',marginLeft:'-316px',marginTop:'-274px'}});}
$(function(){$(".jq-raq-popup-btn").click(showRaqPopup);if($(".jq-raq-popup-btn").length>0){preloadRaqPopup();}});var videoPopupCache={};function showVideoPopup(type){if(!type){type="home";}
if(videoPopupCache[type]){_showVideoPopup(videoPopupCache[type]);return;}
$.ajax({url:'/ajax/video-popup',data:{type:type,format:"html"},async:false,success:function(data){videoPopupCache[type]=data;_showVideoPopup(data);var escapeBtnHandler=function(e){var code=e.keyCode?e.keyCode:e.which;if(code==27){$.unblockUI();}};$(document).unbind('keyup',escapeBtnHandler);$(document).keyup(escapeBtnHandler);},error:function(){showTooltipMessage(Config.generalErrorMessage);}});}
function _showVideoPopup(html){var id="video-popup";var selector="#"+ id;var $video=$(selector);html="<div id=\""+ id+"\" style=\"display: block;\">"+html+"</div>";$.blockUI({message:html,css:{top:'50%',left:'50%',width:'714px',height:'560px',marginLeft:'-357px',marginTop:'-280px'}});}
function makeExpandableText(symbols,selector){if(typeof jQuery=="undefined"||!$.isFunction($("body").expander)){return;}
if(!symbols){symbols=180;}
if(!selector){selector=".sys-expandable-text";}
$(selector).expander({slicePoint:symbols,expandText:"Read More",userCollapseText:"Less"});}
$(document).ready(function(){"use strict";if($('body').hasClass('desktop-mode')){$('.bg-ny').fadeIn(300);$('.loc-ny').addClass('loc-active');$('.location-cell').hover(function(){if(!$(this).hasClass('loc-active')){if($(this).hasClass('loc-ny')){$('.location-cell').removeClass('loc-active');$('.location-area .bg').fadeOut(300);$('.bg-ny').fadeIn(300);$(this).addClass('loc-active');}
if($(this).hasClass('loc-chicago')){$('.location-cell').removeClass('loc-active');$('.location-area .bg').fadeOut(300);$('.bg-chicago').fadeIn(300);$(this).addClass('loc-active');}
if($(this).hasClass('loc-seattle')){$('.location-cell').removeClass('loc-active');$('.location-area .bg').fadeOut(300);$('.bg-seattle').fadeIn(300);$(this).addClass('loc-active');}}});}});